### ISSUE TITLE
triangleHalfHeight viariable not used

### ISSUE THREAD

**Issue by hellonearthis** [Wattenberger/kumiko#1]
triangleHalfHeight could be used here as it's computed earlier and would save doing the * 2 again in the loop.

https://github.com/Wattenberger/kumiko/blob/d3760d2fe001ddc7e9fe931f9c3cf3ecf6cf4ca7/src/components/Canvas.svelte#L118

**Comment by Wattenberger** [comment]
makes sense, thanks!
