### ISSUE TITLE
Optimize patterns

### ISSUE THREAD

**Issue by msurguy** [Wattenberger/kumiko#2]
Hi! Great tool! 

It would help reduce the final SVG size if patterns in https://github.com/Wattenberger/kumiko/tree/master/src/components/patterns are optimized. 

You can use SVGOMG to trim number of decimals / reduce the SVG code by about 50-70%. 
Also, when generating output, you can use my npm package to optimize final SVG by trimming decimals: https://github.com/msurguy/svg-file-downloader. Here's the relevant code: https://github.com/msurguy/svg-file-downloader/blob/master/svg-file-downloader.js

Feel free to add your tool to https://drawingbots.net/knowledge/tools if you'd like!

**Comment by Wattenberger** [comment]
great call, thanks! and I hadn't seen that site before - will definitely add it. This is why I love open sourcing my code!
