### ISSUE TITLE
Link to project in the About section

### ISSUE THREAD

**Issue by msurguy** [Wattenberger/kumiko#3]
Hi! It would be great to have a link to the deployed site from Github, the About section on the repo page would usually be a good spot for that.

For example check out how I have it on some of my tools:

<img width="379" alt="Screen Shot 2021-03-04 at 9 08 22 PM" src="https://user-images.githubusercontent.com/585833/110069960-cfe7b000-7d2d-11eb-9688-3b73c11487ff.png">

Also, tags are good for discovery on Github.

**Comment by Wattenberger** [comment]
good call! I need to fill out the readme, but this is good low-hanging fruit
